using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class YouLost : MonoBehaviour
{
    private void Start()
    {
        GameEvents.instance.onGameLostEvent += ShowYouLostText;
        GameEvents.instance.onGameRestartEvent += HideYouLostText;
    }

    private void ShowYouLostText()
    {
        GetComponent<Animator>().SetBool("YouLostBool", true);
    }

    private void HideYouLostText()
    {
        GetComponent<Animator>().SetBool("YouLostBool", false);
    }
}
